/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type OverallStatus = { 'Stable' : null } |
  { 'Warning' : null } |
  { 'Unstable' : null };
export interface Reading {
  'gas' : bigint,
  'temperature' : number,
  'humidityStatus' : SensorStatus,
  'gasStatus' : SensorStatus,
  'humidity' : number,
  'timestamp' : Timestamp,
  'temperatureStatus' : SensorStatus,
  'overallStatus' : OverallStatus,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type SensorStatus = { 'Stable' : null } |
  { 'Warning' : null } |
  { 'Unstable' : null };
export interface Thresholds {
  'gasWarningMax' : bigint,
  'fluctuationDelta' : number,
  'humidityNormalMax' : number,
  'humidityNormalMin' : number,
  'temperatureWarningMax' : number,
  'temperatureWarningMin' : number,
  'temperatureNormalMax' : number,
  'temperatureNormalMin' : number,
  'humidityWarningMax' : number,
  'humidityWarningMin' : number,
  'gasNormalMax' : bigint,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Advance the simulation by one step and persist the new reading.
   */
  'advanceSimulation' : ActorMethod<[], Reading>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown description of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Current reading, or null before the first simulation step.
   */
  'getCurrentReading' : ActorMethod<[], [] | [Reading]>,
  /**
   * / Bounded recent readings, newest first.
   */
  'getRecentReadings' : ActorMethod<[bigint], Array<Reading>>,
  /**
   * / Predefined thresholds used to derive status.
   */
  'getThresholds' : ActorMethod<[], Thresholds>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];