/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const SensorStatus = IDL.Variant({
  'Stable' : IDL.Null,
  'Warning' : IDL.Null,
  'Unstable' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OverallStatus = IDL.Variant({
  'Stable' : IDL.Null,
  'Warning' : IDL.Null,
  'Unstable' : IDL.Null,
});
export const Reading = IDL.Record({
  'gas' : IDL.Nat,
  'temperature' : IDL.Float64,
  'humidityStatus' : SensorStatus,
  'gasStatus' : SensorStatus,
  'humidity' : IDL.Float64,
  'timestamp' : Timestamp,
  'temperatureStatus' : SensorStatus,
  'overallStatus' : OverallStatus,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Thresholds = IDL.Record({
  'gasWarningMax' : IDL.Nat,
  'fluctuationDelta' : IDL.Float64,
  'humidityNormalMax' : IDL.Float64,
  'humidityNormalMin' : IDL.Float64,
  'temperatureWarningMax' : IDL.Float64,
  'temperatureWarningMin' : IDL.Float64,
  'temperatureNormalMax' : IDL.Float64,
  'temperatureNormalMin' : IDL.Float64,
  'humidityWarningMax' : IDL.Float64,
  'humidityWarningMin' : IDL.Float64,
  'gasNormalMax' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'advanceSimulation' : IDL.Func([], [Reading], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentReading' : IDL.Func([], [IDL.Opt(Reading)], ['query']),
  'getRecentReadings' : IDL.Func([IDL.Nat], [IDL.Vec(Reading)], ['query']),
  'getThresholds' : IDL.Func([], [Thresholds], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const SensorStatus = IDL.Variant({
    'Stable' : IDL.Null,
    'Warning' : IDL.Null,
    'Unstable' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OverallStatus = IDL.Variant({
    'Stable' : IDL.Null,
    'Warning' : IDL.Null,
    'Unstable' : IDL.Null,
  });
  const Reading = IDL.Record({
    'gas' : IDL.Nat,
    'temperature' : IDL.Float64,
    'humidityStatus' : SensorStatus,
    'gasStatus' : SensorStatus,
    'humidity' : IDL.Float64,
    'timestamp' : Timestamp,
    'temperatureStatus' : SensorStatus,
    'overallStatus' : OverallStatus,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Thresholds = IDL.Record({
    'gasWarningMax' : IDL.Nat,
    'fluctuationDelta' : IDL.Float64,
    'humidityNormalMax' : IDL.Float64,
    'humidityNormalMin' : IDL.Float64,
    'temperatureWarningMax' : IDL.Float64,
    'temperatureWarningMin' : IDL.Float64,
    'temperatureNormalMax' : IDL.Float64,
    'temperatureNormalMin' : IDL.Float64,
    'humidityWarningMax' : IDL.Float64,
    'humidityWarningMin' : IDL.Float64,
    'gasNormalMax' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'advanceSimulation' : IDL.Func([], [Reading], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentReading' : IDL.Func([], [IDL.Opt(Reading)], ['query']),
    'getRecentReadings' : IDL.Func([IDL.Nat], [IDL.Vec(Reading)], ['query']),
    'getThresholds' : IDL.Func([], [Thresholds], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };